CREATE TABLE mysql.Referee (
id INT(8) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
firstname VARCHAR(30) NOT NULL,
lastname VARCHAR(30) NOT NULL,
email VARCHAR(50),
phone VARCHAR(10),
grade VARCHAR(2),
reg_date  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE mysql.Games (
id INT(8) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
agegroup_id INT(8) NOT NULL,
starttime timestamp,
location VARCHAR(50),
reg_date  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (agegroup_id)
    REFERENCES mysql.agegroups(id)
);

CREATE TABLE mysql.agegroups (
id INT(8) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
agegroup VARCHAR(30) NOT NULL,
starttime timestamp,
location VARCHAR(50),
reg_date  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
